Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -33,13 +33,16 @@ jobs:
 
       - name: Terraform Action
         run: |
-          if [ "${{ github.event.inputs.tf_action }}" == "plan" ]; then
-            terraform plan
+         if [ "${{ github.event.inputs.tf_action }}" == "plan" ]; then
+          terraform plan -out=tfplan
+
           elif [ "${{ github.event.inputs.tf_action }}" == "apply" ]; then
-            terraform apply
-          elif [ "${{ github.event.inputs.tf_action }}" == "destroy" ]; then
-            terraform destroy
-          else
-            echo "Invalid input"
-            exit 1
-          fi
+           terraform plan -out=tfplan
+           terraform apply tfplan   
+
+           elif [ "${{ github.event.inputs.tf_action }}" == "destroy" ]; then
+            terraform destroy -auto-approve  
+           else
+           echo "Invalid input"
+           exit 1
+       fi
